server:
  port: 8083

spring:
  application:
    name: trusted-content-resolver

logging:
  level:
    root: INFO
    eu.xfsc.train.tcr: DEBUG

tcr:
  did:
#    base-uri: local #http://localhost:8080/1.0
    base-uri: https://dev.uniresolver.io/1.0
    config-path: ../uni-resolver-config.json
    cache:
      size: 0
      timeout: 1H

  dns:
    hosts: []
    timeout: 500
    doh:
      enabled: false
    dnssec:
      enabled: false
      rootPath: ""

  tl:
    cache:
      size: 0
      timeout: 1H

  trust:
    anchors:
      - did:web:localhost%3A8081

    lists:
      http:
        - pointer: did:web:localhost%3A8081
          location: http://localhost:8081/trust/trust-list.json
